### ISSUE TITLE
Improve type resolving

### ISSUE THREAD

**Issue by Maximilien-R** [tartiflette/tartiflette#122]
Since `tartiflette` allow us to deal only with `dict`. Resolving the `__typename` field for an `UnionType` is difficult and is delegate to the `Resolver` implementation which need to return the `__typename` in the resolved value.

Maybe we could add an optional `resolve_type` argument to the `Resolver` decorator which could take a callable in charge of determining the `__typename` to return for the resolved value? This `resolve_type` parameter could be required for an `UnionType` resolver which returns a value where the `__typename` couldn't be resolved by the default `resolve_type` function (a `dict` without a `__typename` key for instance).

```python
@Resolver(
    "Query.catOrDog",
    resolve_type=lambda result: "Dog" if is_dog(result) else "Cat",
)
def query_cat_or_dog_resolver(*_args, **_kwargs):
    return {
        "name": "Dogo",
    }
```

**Comment by abusi** [comment]
I kind of like this idea @Maximilien-R.
@tsunammis what do you think of this idea?

I think it's great to enable our users to override the current default behavior.
