### ISSUE TITLE
[Extensibility through @directive] hook's specification

### ISSUE THREAD

**Issue by tsunammis** [tartiflette/tartiflette#224]
The [June2018 GraphQL Specification](https://github.com/graphql/graphql-spec/blob/June2018/spec/Section%203%20--%20Type%20System.md#directives) described an interesting list of locations where directive could be applied on.

## Context

As [explained in the website](https://tartiflette.io/docs/tutorial/extend-with-directives), **tartiflette** based its extensibility on the directive mechanism.

The current version of `tartiflette` _(< 1.0.0)_ provides some "hooks" through the directives.

* **Event:** `On build` -> which calls the method [`on_build(schema: "GraphQLSchema")` of the directive](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/directive/common.py#L10).
* **Event:** `On field execution` -> which calls the method [`on_field_execution( ... )` of the directive](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/directive/common.py#L26)
* **Event:**  `On argument execution` -> which calls the  method [`on_argument_execution( ... )` of the directive](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/directive/common.py#L48)
* **Event:**  `On introspection` -> which calls the  method [`on_introspection( ... )` of the directive](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/directive/common.py#L77)

These hooks allow the developers to implement some interesting behavior, e.g:
* Apply some validation rules on input argument with the event `On argument execution`
* Change the behavior of the introspection by hiding some fields with the event `On introspection`
* Add access rules on field with the event `On field execution`

## Objective

The main objective of this issue is to discuss the next **Directive API** which will allow us to apply directives on all the locations listed by the [GraphQL Specification](https://github.com/graphql/graphql-spec/blob/June2018/spec/Section%203%20--%20Type%20System.md#directives), both on the `ExecutableDirectiveLocation` and `TypeSystemDirectiveLocation`.

#### TypeSystem Directive

| Directive Method name _(hook)_   | Schema | Scalar | Object | Field Definition | Argument Definition | Interface | Union | Enum | Enum Value | Input Object | Input Field Definition |
| -------------------------------- | ------ | ------ | ------ | ---------------- | ------------------- | --------- | ----- | ---- | ---------- | ------------ | ---------------------- |
| on_schema_execution              | X      |        |        |                  |                     |           |       |      |            |              |                        |
| on_scalar_argument_execution     |        | X      |        |                  |                     |           |       |      |            |              |                        |
| on_scalar_field_execution        |        | X      |        |                  |                     |           |       |      |            |              |                        |
| on_object_execution              |        |        | X      |                  |                     |           |       |      |            |              |                        |
| on_field_execution               |        |        |        | X                |                     |           |       |      |            |              |                        |
| on_argument_execution            |        |        |        |                  | X                   |           |       |      |            |              | X                      |
| on_interface_execution           |        |        |        |                  |                     | X         |       |      |            |              |                        |
| on_union_execution               |        |        |        |                  |                     |           | X     |      |            |              |                        |
| on_enum_argument_execution       |        |        |        |                  |                     |           |       | X    |            |              |                        |
| on_enum_field_execution          |        |        |        |                  |                     |           |       | X    |            |              |                        |
| on_enum_value_argument_execution |        |        |        |                  |                     |           |       |      | X          |              |                        |
| on_enum_value_field_execution    |        |        |        |                  |                     |           |       |      | X          |              |                        |
| on_input_object_execution        |        |        |        |                  |                     |           |       |      |            | X            |                        |
| on_introspection                 | X      | X      | X      | X                | X                   | X         | X     | X    | X          | X            | X                      |
| on_build                         | X      | X      | X      | X                | X                   | X         | X     | X    | X          | X            | X                      |

#### Executable Directive

| Directive Method name _(hook)_ | Query | Mutation | Subscription | Field | Fragment Definition | Fragment Spread | Inline Fragment |
| ------------------------------ | ----- | -------- | ------------ | ----- | ------------------- | --------------- | --------------- |
| on_operation_execution         | X     | X        | X            |       |                     |                 |                 |
| on_field_execution             |       |          |              | X     |                     |                 |                 |
| on_fragment_execution          |       |          |              |       | X                   | X               |                 |
| on_inline_fragment_execution   |       |          |              |       |                     |                 | X               |

### Next

1. Define the execution's order.
2. Define the signature of each methods.

**Comment by abusi** [comment]
Next step here is to specify the execution order of all these hooks.
I'll have a proposal soon. If anyone has idea, i'll look at them with pleasure.

**Comment by florimondmanca** [comment]
This sounds great. Directives look like a huge step forward to enhance extensibility of Tartiflette going forward.

Just to be sure — an X in the above tables means that the hook accepts the corresponding input as a parameter, right?

Also, I see hooks currently use a 100% positional style, e.g.:

[`on_field_execution(directive_args, next_resolver, parent_result, args, ctx, info)`](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/directive/common.py#L26)

Again, is there any way to lessen the verbosity of these signatures? I see some arguments are common to many hooks — perhaps they could be stored in the directive itself (via its `__init__()` method), and we'd access them via `self.xyz` instead? Maybe these signatures are just necessary.

**Comment by abusi** [comment]
```Again, is there any way to lessen the verbosity of these signatures? I see some arguments are common to many hooks — perhaps they could be stored in the directive itself (via its __init__() method), and we'd access them via self.xyz instead? Maybe these signatures are just necessary.
```
We're going to transform the `static` directives into instance ones.
This will enable us to simply a lot these signatures. At least, `directive_args` and `next` are going to move into the instance.
We are also thinking on a way to provide configuration to a directive instance.
I'm working on a little PR to prove some concepts (see #223) and then I'll have a more precise idea on how to `solve` this feature.

**Comment by abusi** [comment]
#223 #226 Will bring an implementation of some `TypeSystem` Directive hook such has :

| Directive Method name _(hook)_ | Schema | Scalar | Object | Field Definition | Argument Definition | Interface | Union | Enum | Enum Value | Input Object | Input Field Definition |
| ------------------------------ | ------ | ------ | ------ | ---------------- | ------------------- | --------- | ----- | ---- | ---------- | ------------ | ---------------------- |
| on_post_input_coercion         |        | X      |        |                  |                     |           |       | X    | X          | X            |                        |
| on_pre_output_coercion         |        | X      | X      |                  |                     |           |       | X    | X          |              |                        |
| on_field_execution             |        |        |        | X                |                     |           |       |      |            |              |                        |
| on_argument_execution          |        |        |        |                  | X                   |           |       |      |            |              | X                      |
| on_introspection               | X      | X      | X      | X                | X                   | X         | X     | X    | X          | X            | X                      |


This approach simplify the Hook System for directive implementation.

The execution flow will be such as:

![ExecutionOrder (2)](https://user-images.githubusercontent.com/7234737/57687912-961b5600-763c-11e9-9676-be93493a6ce3.png)

`Type` and `Value` applies only for `ENUM` and `ENUM_VALUE`, for all other cases `on_post_input_coercion` and `on_pre_output_coercion` are only called once, for the `Type`.

This will be delivered in 0.10.0, then from here we'll try to tackle the `Interface`, `Union`, `Schema`, and the `on_build` hook.

**Comment by tsunammis** [comment]
In addition to these improvements, we started to make third-party libraries possible -> https://github.com/dailymotion/tartiflette/issues/228

**Comment by abusi** [comment]
#272 will be a big step toward this.
It will only miss #134 which will be schedule next.
I'll mark this for v1.1 milestone.

**Comment by abusi** [comment]
I think this is done now when #383 will be merged. I'll mark it as closed.
