### ISSUE TITLE
Broken cyrillic descriptions in GraphQL schemas

### ISSUE THREAD

**Issue by dmitry-sobolev** [tartiflette/tartiflette#245]
When I trying to write descriptions in graphql schemas in russian, e.g.:
```graphql
type Query { 
"тест" 
test: Boolean 
} 
```
It will be parsed into `Ñ\x82ÐµÑ\x81Ñ\x82`. I expected that description will be readable.

While debugging I found that corruption is result of execution these lines: https://github.com/tartiflette/tartiflette/blob/d07a3444d6abc82e25175c1c42b128b8d611bba4/tartiflette/sdl/transformers/cleaning_transformer.py#L67 and https://github.com/tartiflette/tartiflette/blob/d07a3444d6abc82e25175c1c42b128b8d611bba4/tartiflette/sdl/transformers/cleaning_transformer.py#L72

* **Tartiflette version:** 0.11.1
* **Python version:** 3.7
* **Executed in docker:** NO
* **Is it a regression from a previous versions?** No

**Comment by abusi** [comment]
@dmitry-sobolev Hi, hum, this is sad. Do you see a way for us to fix this ?
I'll have a tendancy to say that we are only supporting UTF-8 encoded file but I don't know if Russian chars can be encoded that way ?
I'll have a look and see if we can specify an encoding for the tartiflette file sdl so you'll be able to create an engine and specify that your SDL are xxx encoded.
What do you think ?

**Comment by abusi** [comment]
which web server are you using ?
which encoding is you file using ?
After reading the SDL file, the python dict should contain the correct represenation of the data.
Then quering the `query { __type(name: \"Query\") { description name fields { name description } } }` through vanilla json.dumps will "encode" to UTF-8 per default with `ensure_ascii=True`  This should be modified for it to work properly if you want a different encoding, but this should be done in the code that integrate tartiflette. 
Can you give me more context so I can find a more general solution here.
First thing should be to let you give the file encoding you want to use here : https://github.com/tartiflette/tartiflette/blob/master/tartiflette/schema/registry.py#L85

**Comment by dmitry-sobolev** [comment]
@abusi File encoded in UTF-8.
Here I've tried to implement script that reproduces my case: https://gist.github.com/dmitry-sobolev/c35d1854b75379de5bd8b9c00740881f. 

As you can see docstring of field `test` in `result.json` is `"\u00d1\u0082\u00d0\u00b5\u00d1\u0081\u00d1\u0082"`. If you try to execute `json.loads('"\u00d1\u0082\u00d0\u00b5\u00d1\u0081\u00d1\u0082"')`, result will be `Ñ\x82ÐµÑ\x81Ñ\x82`. I think this is incorrect behavior because input string already was been in UTF-8. 
Actually, I can't suggest possible solution because I don't understand why this statement was wrote: 
https://github.com/tartiflette/tartiflette/blob/d07a3444d6abc82e25175c1c42b128b8d611bba4/tartiflette/sdl/transformers/cleaning_transformer.py#L67
Why don't just write something like:
```python
cleaned_str = token.value[1:-1]
```
it will be correctly converted to json.

**Comment by abusi** [comment]
Thanks for your information, i'll have a look at it.
I Honestly I can't remember why we did it that way.

**Comment by dmitry-sobolev** [comment]
Thanks :)

**Comment by abusi** [comment]
No problem thank you for the bug report, we'll release a 0.12.x or a 0.11.x soon :tm:
