### ISSUE TITLE
Batch loading

### ISSUE THREAD

**Issue by dmitry-sobolev** [tartiflette/tartiflette#276]
Hello,

I've created schema with type which fields has resolvers. It means that if I query e.g. 5 objects of this type every resolver will be executed 5 times. If every resolver contains request to db, result will be 1+5*(number of resolvers) requests, which is quite many. Is there any way to implement batch loading of nested resolvers or maybe another way to optimize number of requests?

**Example**

SDL:
```graphql
type User {
  id: ID!
  name: String!
  friends(number: Int!): [User!]!
}

type Query {
  users(number: Int!): [User!]!
}
```

Query:
```graphql
{
  users(number: 5) {
    id
    name
    friends(number: 5) {
      id
      name
    }
  }
}
```

```python
@Resolver('Query.users')
async def get_users(parent, args, context, info):
    return await get_users_from_db(limit=args.get('number', 5))  # executed 1 time

@Resolver('User.friends')
async def get_friends(parent, args, context, info):
    return await get_friends_from_db(user_id=parent.get('id'), limit=args.get('number', 5))  #executed 5 times

```

**Comment by tsunammis** [comment]
Hello @dmitry-sobolev 

Thank you for your question.

> Is there any way to implement batch loading of nested resolvers or maybe another way to optimize number of requests?

Currently, there is no way to optimize or to implement a batching solution within the tartiflette engine.

### How are we dealing with the [N+1 problem](https://engineering.shopify.com/blogs/engineering/solving-the-n-1-problem-for-graphql-through-batching)? 

When we started to implement a GraphQL API, internally, we decided to build a DataLoader to batch, optimize and cache the data loading process, thus, even after our migration from graphene to tartiflette, we are still using our own dataloader. We didn't face the N+1 problem, yet.

**Comment by dmitry-sobolev** [comment]
Ok, I understood.

Thank you for answer.
