### ISSUE TITLE
Interface __typename not supported, nested "... on" error

### ISSUE THREAD

**Issue by aljinovic** [tartiflette/tartiflette#277]
I found 2 different problems with query processing:

1. `__typename` doesn't work on Interfaces
1. `field ... was not found in GraphQL schema` error occurs on the first next field after a nested `... on` statement in the query

**Schema**
```graphql
schema {
    query: RootQuery
}

type RootQuery {
    vehicles: Vehicle
}

type Model {
    name: String
}

interface Vehicle {
    color: Color
}

type Car implements Vehicle {
    color: Color
    model: Model
}

interface Color {
    rgb: String
}

type Blue implements Color {
    rgb: String
}
```

**Query**
```graphql
{
  vehicles
  {
    __typename
    ... on Car {
      color {
        ... on Blue {
          rgb
        }
      }
      model {
        name
      }
    }
  }
}
```

**Errors**
```json
{
  "data": null,
  "errors": [
    {
      "message": "field `Vehicle.__typename` was not found in GraphQL schema.",
      "path": [
        "vehicles",
        "__typename"
      ],
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    },
    {
      "message": "field `Vehicle.model` was not found in GraphQL schema.",
      "path": [
        "vehicles",
        "model"
      ],
      "locations": [
        {
          "line": 11,
          "column": 7
        }
      ]
    }
  ]
}
```

**Tartiflette version:** 0.12.4
**Python version:** 3.7
**Executed in docker:** Yes, but same problem reproducible when executed outside.
**Is it a regression from a previous versions?** No

**Comment by tsunammis** [comment]
Thank you @aljinovic for your bug report.

This issue will be solved by the tartiflette version 1 we are working on. [More details on this pull-request](https://github.com/tartiflette/tartiflette/pull/272).

In the tartiflette version 1, the entire execution algorithm has been rewritten, giving us the ability to be compliant with the GraphQL Specification June 2018.

The tartiflette version 1 will be release early in september.

**Comment by aljinovic** [comment]
Do you maybe have a build which I could test?

**Comment by abusi** [comment]
@aljinovic you can test this by doing `git checkout  ISSUE-121-document-node-execution` and then `pip install -e .` in a cleab vituralenv. Then you'll be able to test it.
Release of alpha v1 is plan next week.
