### ISSUE TITLE
`extend type` is ignored

### ISSUE THREAD

**Issue by remorses** [tartiflette/tartiflette#278]
Extended fields are ignored
```graphql
type Query {
    hello: String
}

extend type Query {
    world: String
}
```

The generated graphql schema contains only hello

![Schermata 2019-08-24 alle 15 49 34](https://user-images.githubusercontent.com/31321188/63638303-c84e4200-c686-11e9-826e-0b352b3dbd0a.png)

**Comment by abusi** [comment]
Yes, it's not supported rigth now, will be done shortly after v1 release.
