### ISSUE TITLE
parse_schema_to_sdl or transform_schema_to_sdl functions?

### ISSUE THREAD

**Issue by shalseban** [tartiflette/tartiflette#297]
**Context**
I want to do some `sdl` manipulation programmatically (on registration of a resovler). This involves adding a new field to an object or changing the type of an existing object. I was planning on doing this by parsing the `GraphQLSchema` object. 

I came across the experimental feature in [lark for reconstruction](https://github.com/lark-parser/lark/blob/master/lark/reconstruct.py) though it fails with `AttributeError: 'WriteTokensTransformer' object has no attribute 'document'`. 

Curious if it is possible to create the `ast` from `GraphQLSchema` or even better the `sdl` from `GraphQLSchema`.

**Comment by abusi** [comment]
Hi @shalseban, what you want to do is not doable right via Tartiflette.
Tartiflette parse the SDL with the language.lark package into Nodes that are used to complete the GraphQLSchema object. 
This GraphQLSchema object is then `bake`.
Then it is usable by the Engine to Resolve a GQLQuery.

The bake process is done once at init time (via the create_engine and cook method). Then the GraphQLSchema is not functionally mutable. What I mean is that you'll be able to modify thing in it (you know, python :p), but as these modification aren't baked (prepared) they won't fully work or it will break other things.

If you want to interact programmatically with your SDL, then maybe you should look at the CodeFirst approach (Tartiflette is SDL First, and we don't plan to support CodeFirst ever).

BUT we are working on a hook for directives to be called at `bake` time which would allow you to add field and other SDL Oriented object to the schema before it is baked. But it will be a one time thing. Not for each request or thing like that.

So if you want to add object and thing like that for each request -> go CodeFirst
If you wanna do it once before the engine start -> wait for 1.1, it's commmming soon :tm:

**Comment by shalseban** [comment]
@abusi 

Thank you for that explanation. That makes sense. I am not exactly trying to do a CodeFirst approach but I see why it seems like it. The `directive` approach might be helpful and will look forward to it. :)

To give more clarity just in case you are interested:
I was planning on mutating the `GraphQLSchema` object and re`cook`ing to ensure everything works as required.  I am trying to keep the GraphQL server very lean without storing any `code`/ `sdl` in the server itself and wanted a programmatic way to modify the `sdl` when a resovler is registered to it, at which point the existing `sdl` is modified and the `engine` is re `cook`ed. 

Now that I think of it. I just wanted to modify the `sdl` and not use regular expressions to do validations on it. So I should work with the `ast` rather than the `GraphQLSchema` object.
