### ISSUE TITLE
Wrong operator in tutorial

### ISSUE THREAD

**Issue by helio-correia** [tartiflette/tartiflette#298]
Hi there, on the tutorial page in docs/tutorial/write-your-mutation-resolvers.md in the part
```
if not (name and cooking_time):
        raise Exception(
            "You should provide at lease one value for eather name or " "cookingTime."
        )
```
This should not be an "or" instead the "and" ?

**Comment by abusi** [comment]
@helio-correia Hi, thank you for reporting this. Do you wanna do a PR in the https://github.com/tartiflette/tartiflette-aiohttp-tutorial repository for fixing the code and one here to fix the doc ?

**Comment by abusi** [comment]
@helio-correia only the doc need to be fixed here. A PR in the tutorial repo is being made.
