### ISSUE TITLE
Provide a manylinux and macos bdist_wheel

### ISSUE THREAD

**Issue by abusi** [tartiflette/tartiflette#320]
Modify the setup.py so it produce bdist_wheel for manylinux including the libgraphqlparser.so/a
Modify the build process so this wheel is uploaded to pypi
Modify the cffi part of tartiflette/parser so it loads this lib instead of the local one.

**Comment by siejqa** [comment]
Hi @abusi,  can I start working on this?

**Comment by abusi** [comment]
@siejqa Yes you can, with pleasure.

**Comment by remorses** [comment]
I am taking care of this, pull coming soon

**Comment by abusi** [comment]
Tartiflette 1.4.0 comes with wheels ! :tada:
