### ISSUE TITLE
Consider display on graphql.org?

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette#325]
The [Code](https://graphql.org/code/) page on the GraphQL website lists GraphQL engines and clients for a variety of languages.

Now that Tartiflette reached v1, should there be a push to have Tartiflette listed on the [Python section](https://graphql.org/code/#python)? :-) Currently, only Graphene is listed there.

I believe the relevant code is [here](https://github.com/graphql/graphql.github.io/blob/source/site/code/index.html.js).

**Comment by tsunammis** [comment]
@florimondmanca there is already an open pull-request -> https://github.com/graphql/graphql.github.io/pull/673/files

I'll update it with `tartiflette-asgi`.

**Comment by erdnaxeli** [comment]
This ticket can be closed, Tartflette is in the python section.

**Comment by abusi** [comment]
@erdnaxeli Thanks, closing it.
