### ISSUE TITLE
Tartiflette fails to build libgraphqlparser on install

### ISSUE THREAD

**Issue by jamessmith-decisionlab** [tartiflette/tartiflette#331]
* Tartiflette fails to build libgraphqlparser on install.
* Python version is 3.7.4
* Not executed in Docker, but here is the trace:

```
Command ['/Users/james.smith/Library/Caches/pypoetry/virtualenvs/ttftt-recipies-manager-CjYWEP0q-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', 'tartiflette==1.1.1'] errored with the following return code 1, and output: 
Collecting tartiflette==1.1.1
  Using cached https://files.pythonhosted.org/packages/4e/ef/311d95c46dd59c0eebad9db11f8ba74ec010f59df5bd9cab88a7bac09dfb/tartiflette-1.1.1.tar.gz
Installing collected packages: tartiflette
  Running setup.py install for tartiflette: started
    Running setup.py install for tartiflette: finished with status 'error'
    Complete output from command /Users/james.smith/Library/Caches/pypoetry/virtualenvs/ttftt-recipies-manager-CjYWEP0q-py3.7/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/27/6lbgh3fs1j5856dfvhf024fw0000gp/T/pip-install-2o0hke12/tartiflette/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/27/6lbgh3fs1j5856dfvhf024fw0000gp/T/pip-record-27b2k_v5/install-record.txt --single-version-externally-managed --compile --install-headers /Users/james.smith/Library/Caches/pypoetry/virtualenvs/ttftt-recipies-manager-CjYWEP0q-py3.7/include/site/python3.7/tartiflette:
    running install
    running build
    running build_py
    CMake Error at CMakeLists.txt:27 (FILE):
      FILE COPY given no DESTINATION
    
    
    make: *** No targets specified and no makefile found.  Stop.
    Libgraphqlparser compilation has failed
    
    ----------------------------------------
Command "/Users/james.smith/Library/Caches/pypoetry/virtualenvs/ttftt-recipies-manager-CjYWEP0q-py3.7/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/27/6lbgh3fs1j5856dfvhf024fw0000gp/T/pip-install-2o0hke12/tartiflette/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/27/6lbgh3fs1j5856dfvhf024fw0000gp/T/pip-record-27b2k_v5/install-record.txt --single-version-externally-managed --compile --install-headers /Users/james.smith/Library/Caches/pypoetry/virtualenvs/ttftt-recipies-manager-CjYWEP0q-py3.7/include/site/python3.7/tartiflette" failed with error code 255 in /private/var/folders/27/6lbgh3fs1j5856dfvhf024fw0000gp/T/pip-install-2o0hke12/tartiflette/
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jamessmith-decisionlab** [comment]
I can't offer much wisdom on why `cmake` would fail to build, I'm afraid. Perhaps this has something to do with Python? I did try to build `libgraphqlparser` from source, and it complained that I was using Python@3.

**Comment by dmitry-sobolev** [comment]
Did you install all dependencies from [README](https://github.com/tartiflette/tartiflette#installation-dependencies)? I've had similar error and it was solved when I installed these packages.

**Comment by jamessmith-decisionlab** [comment]
I have `cmake` version 3.15.5, `flex` version 2.5.35 and `bison` version 2.3 installed.

A few observations...

1. Mac users can install `libgraphqlparser` directly with Homebrew. I'm sure Linux users can install it, too. Therefore, could you not get the installation script to check whether `libgraphqlparser` is present on the path before attempting to build it?

2. I did clone and then try to build the`libgraphqlparser` project separately. It complained that it needed `bison` version 3, not 2. So can you confirm what version of Bison you are using?

Many thanks.

**Comment by dmitry-sobolev** [comment]
On my host machine (Ubuntu 18.04):
* `bison` version 3.0.4
* `flex` version 2.6.4
* `cmake` version 3.10.2

In docker (`python:3.8-alpine`):
* `bison` version 3.3.2
* `flex` version 2.6.4
* `cmake` version 3.14.5

**Comment by jamessmith-decisionlab** [comment]
Thanks!

Let me see if I can get `bison` version 3 installed. Homebrew doesn't want to do it, but I'll find another way.

**Comment by jamessmith-decisionlab** [comment]
Do you have any comment to make on the first point I made, namely your installation script checking to see whether or not `libgraphqlparser` is already installed?

**Comment by Maximilien-R** [comment]
Hi @jamessmith-decisionlab,

You shouldn't have to build `libgraphqlparser` from source, especially since we have our own version of it. When installing `tartiflette` it'll build `libgraphqlparser` on its own (that's why you need `cmake`, `flex` & `bison` as dependecies.

There is a known issue on macOS when installing `bison` from `brew`. When installed through `brew`, the `bison` version used by default is the one builtin with macOS. Maybe your issue is related to this. You can take a look on this Stackoverflow comment to help you (cf. https://stackoverflow.com/questions/10778905/why-does-my-mac-os-x-10-7-3-have-an-old-version-2-3-of-gnu-bison/30844621#30844621)

If this isn't helpful maybe @abusi could have another solution?

**Comment by jamessmith-decisionlab** [comment]
Forcing version 3 of `bison` to take priority indeed got the install working.

I'll add my thoughts on how to do that below for the sake of anyone else coming here.

In fact, Homebrew already had it installed. I don't quite know the ins and outs of it, the StackOverflow answer you pointed out is a little confusing. However, in fairness, it does point out that you can force version 3 of `bison` to be used by adding it to your path explicitly in the usual way, namely amending the path in your `.bash_profile` file. I added this line:

'''
export PATH="/usr/local/opt/bison/bin:$PATH"
'''

Many thanks.

**Comment by abusi** [comment]
@jamessmith-decisionlab also we have this issue #320 that should remove these build deps, if you have some insight on how we could do it, you could comment on it.
Thanks for raising this issue, thank you @dmitry-sobolev and @Maximilien-R for the help.

**Comment by jamessmith-decisionlab** [comment]
Thanks @abusi. I can't offer any insights, I'm afraid, this is far from my areas of expertise.
