### ISSUE TITLE
Extensibility without directives

### ISSUE THREAD

**Issue by dmbasso** [tartiflette/tartiflette#337]
Hello, first of all, thank you for your work. I'm wondering how (if at all currently possible) to hookup field execution on a global level; the use-case is pretty easy to explain: I want *all* queries, mutations, and subscriptions to be access restricted by default, and directives would be used to loosen the restrictions on a case-by-case basis. Is that possible with Tartiflette's current API?

**Comment by abusi** [comment]
Hi in Tartiflette 1.1.1 you could implement a directive with a `on_schema_excution` and `on_schema_subscription` hooks. This will be called before the request is executed or the subscription generated. 
Then on your sdl you'll have:
```
Schema @mycustomdirective{
query: query
mutation: mutation
subscription: subscription
}
```
Or
```
extend schema @mycusomdirective
```

I think there is some doc somewhere about this.

**Comment by abusi** [comment]
https://tartiflette.io/docs/api/directive should have all the info you need.

As the graph is resolving parent before child we can deny then allow some child. If the root node is deny, then the whole tree is denied.

**Comment by dmbasso** [comment]
Thanks for the clarification, I was not aware of the schema directives.
If I understood correctly, all access restriction logic would have to be put in on_schema_(subscription|execution), where I'd have to traverse the document and collect the field directives that were parsed (as I can't use the on_field_execution because it is processed later on the pipeline). I'll try to implement it. But I was hoping there would be a simpler way, like a 'default field directive', which is implied if no explicit field directive is attached to a field.

**Comment by abusi** [comment]
@dmbasso, I'm not really sure I've understood what you're trying to achieve.

```
 But I was hoping there would be a simpler way, like a 'default field directive', which is implied if no explicit field directive is attached to a field.
```

I'm not in favor of this. I prefer for things to be explicit, you add the @dir to the node you want.
Note that you can also add directive to type/interface which could allievate the fact that you need to mark each node.
