### ISSUE TITLE
An object type must be a super‐set of all interfaces it implements

### ISSUE THREAD

**Issue by Maximilien-R** [tartiflette/tartiflette#372]
* **Tartiflette version:** 1.1.3
* **Python version:** 3.7.6
* **Executed in docker:** No
* **Is a regression from a previous versions?** No

> The object field must be of a type which is equal to or a sub‐type of the interface field (covariant).

Seems like the validation regarding object fields isn't properly implemented.

For example:
```graphql
interface MediaMetadata {
  height: Int
  width : Int
}

interface Media {
  metadata: MediaMetadata
}

type VideoMetadata implements MediaMetadata {
  height: Int
  width : Int
  duration: Int
}

type Video implements Media {
  metadata: VideoMetadata
}

type Live implements Media {
  metadata: MediaMetadata
}

type Query {
  media: Media
}
```

`Video.metadata` raise the following error:
```
tartiflette.types.exceptions.tartiflette.GraphQLSchemaError:

0: Field < Video.metadata > should be of Type < MediaMetadata > as defined in the < Media > Interface.
```

However, `VideoMetadata` is a possible type of `MediaMetadata` interface which, regarding the [GraphQL specification](http://spec.graphql.org/June2018/#sec-Objects) should be valid:
> An object field type is a valid sub‐type if it is an Object type and the interface field type is either an Interface type or a Union type and the object field type is a possible type of the interface field type.

**Comment by abusi** [comment]
Will work on it ASAP, schema validation is not really up "to spec". We did a big effort on Query validation. Seems that Schema one also needs some love.
