### ISSUE TITLE
Want a directive to run on INPUT_FIELD_DEFINITION with access to query argument values

### ISSUE THREAD

**Issue by jalelegenda** [tartiflette/tartiflette#378]
## Want a directive to run on input field definition and be able to access `args`

I have this case
```
# the sdl
schema {
  query: RootQuery
}

directive @exclusive(dependant: String!) on INPUT_FIELD_DEFINITION

type RootQuery {
  inputType: inputTypeField
  ...
}

input inputType {
  inputField1: String @exclusive("inputField2")
  inputField2: String @exclusive("inputField1")
}
```

```
# python
@Directive("exclusive")
class Exclusive:
  async def on_field_definition(directive_args, next, parent, args, ctx, info):

    ###################################################################################
    # if this could run when inputField1 or inputField2 are specified that'd be grrreat
    ###################################################################################

    if directive_args["dependant"] in args:
      raise Error
```

If there's a way to make the above scenario work, without mucking up the resolver, I'd gladly try it.
I've also tried with FIELD_DEFINITION, but that's illegal, as far as I can tell.

**Comment by jalelegenda** [comment]
I've solved this with a combination of INPUT_OBJECT on the parent input type and FIELD_DEFINITION on the resolving type. I'll leave this issue open for you guys to consider. Feel free to close it, though.

**Comment by abusi** [comment]
Hi @jalelegenda 
Can you paste a copy of your solution ?
Thanks you.

**Comment by jalelegenda** [comment]
Sure thing @abusi. Here's what I did:

```
# the sdl
directive @exclusive on INPUT_OBJECT | FIELD_DEFINITION

schema {
  query(someInput: InputType): RootQuery @exclusive
}

type RootQuery {
  ...
}

input inputType @exclusive {
  inputField1: String
  inputField2: String
}
```
On the schema I defined a directive that will be placed on the field of the query and on the input type, that's used in the same query, containing the parameters we want to limit.

```
@Directive("exclusive")
class Exclusive:
  _exclusive_pairs = (
    ("inputField1", "inputField2"),
    ...
  )

  async def on_post_input_coercion(self, directive_args, next_directive, parent_node, value, ctx):
    for include_pair, exclude_pair in self._exclusive_pairs:
      if value.get(include_pair) and value.get(exclude_pair):
        ctx["exclusive_pairs_defined_error"] = SomeError

  return await next_directive(parent_node, value, ctx)

  async def on_field_execution(self, directive_args, next_resolver, parent, args, ctx, info):
    """Raise error in case it exists inside the `ctx` object."""
    if ctx.get("exclusive_pairs_defined_error"):
        raise ctx["exclusive_pairs_defined_error"]

    return await next_resolver(parent, args, ctx, info)
```
The idea is that once the input type has been coerced, we check inside the value dictionary whether it contains the exclusive pairs, which I defined inside the directive class. If it does, the method places an error object inside the `ctx` object.
Before the field is resolved the second directive runs and checks if there is an error inside the `ctx` object and raises it in case one exists.
