### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by lishine** [tartiflette/tartiflette#404]
Is there a redis subscription example?
#123 still relevant?

**Comment by abusi** [comment]
Hi @lishine can you be a little bit more specific ?
I don't think we have any redis based subscription example available.
Maybe @Maximilien-R have some ?

**Comment by lishine** [comment]
The inlcuded example in the docs is a generator.
How to integrate it with pubsub like redis.

**Comment by abusi** [comment]
The way I see this is, first before the async for, on client connection, you pub into a redis pubsub to notify your server that you are ready, then he sends you a new "pubsub" name were you sub and then you do async for message.wait(), then you should be able to yield all messages to the subscription client.
