### ISSUE TITLE
Types generation

### ISSUE THREAD

**Issue by lishine** [tartiflette/tartiflette#406]
Is there an approach for types generation from the scheme?

**Comment by abusi** [comment]
Can you be more explicit ?

**Comment by lishine** [comment]
Generate the types of resolver parameters from the types in the scheme.
The graphql-code-generator does not generate types for python.

**Comment by abusi** [comment]
You want something that generate python code from SDL Scheme ? It is not yet available in Tartiflette, https://github.com/tartiflette/tartiflette/issues/390 should take care of this.

BUT for tartiflette, you do not need to have types, your resolver can return dict, it will still work.

**Comment by lishine** [comment]
More like types generation.
With typescript, types of the resolvers are generated, then imported as Resolvers and used like this:
```
export resolvers: Resolvers = {
  resolverA(context, args, info) {
  }
}
```
No need to annotate types the resolver or their params.
The resolver names and parameters get type checking and intellisense.

**Comment by abusi** [comment]
Yeah, It doesn't exists yet for tartiflette, you have to annotate your code manually.
