### ISSUE TITLE
ERROR: Failed building wheel for tartiflette

### ISSUE THREAD

**Issue by themasterking90** [tartiflette/tartiflette#417]
Do you want to **report a bug?** or **request a feature?**, please keep the corresponding template.

## Report a bug

Please provide the steps to reproduce your problem and, if possible, a full reproducible environment. **As we are working directly with containers, please provide the Dockerfile sample or the Docker image name**

*  **Python version:** _3.8.1_
*  **Pip version:** _20.2_

DEPRECATION: Could not build wheels for tartiflette which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

**Comment by abusi** [comment]
@themasterking90 thanks for bringing this to our attention,
Can you provide a PR in order to fix this ?

**Comment by abusi** [comment]
tartiflette 1.4.0 comes with wheels :) this is fixed now :D
