### ISSUE TITLE
Middlewares?

### ISSUE THREAD

**Issue by sebastiandev** [tartiflette/tartiflette#452]
## Request a feature
From the docs and the code I can't seem o find a way of defining middlewares. I wouldn't want to do it with directives as I would have to manually decorate every operation.  The only way I can think of is by extending the `Resolver` decorator and adding the middleware logic there, although that's not a real middlware. 

Are there any plans to add this? Other GraphQL libraries already provide that (graphene, ariadne, etc)

Thanks

**Comment by sebastiandev** [comment]
Alright, I think I found something deep in the docs
```
New in 1.1.0:
    on_schema_execution: allows you to wrap the execution of a request (QUERY or MUTATION) in order to manipulate the initial_value or add extensions to the global result dict.
```
Is this the suggested way of adding middlewares?

**Comment by abusi** [comment]
Hi @sebastiandev, the "middleware" paradigm can be achieve through on_schema_execution directives. 
But, IMHO, middleware is a thing for the HTTPEngine, not really for the graphql query executor, because the graphql way to extend behavior is via Directive. With the idea of Schema Directive we thought that it could bring a "middleware" like feature while still being rigth in the GraphQL way of thing.

But i'm open to discussion on this. what do you think ?

**Comment by sebastiandev** [comment]
@abusi thanks for getting back. Well, I just found the  `on_schema` directive after creating the issue. That seems like it would solve the issue. The middleware thing is a bit more universal and easier to pick up conceptually. Also the other graphql libraries have middlewares so maybe that contributes to the confusion. I think some docs with some concrete examples would be great for those coming from graphene (like me) or maybe even mentioning middlewares and explaining the tartiflette way of doing it.

I usually use this to inject data to the context, auth, etc. 

For context, I've encounter difficulties implementing auth for tartiflette apps with FastAPI since the tartiflette-asgi app is meant to be mounted, making the use of injected dependencies to paths impossible. Although I could achieve auth in general with a middleware at the http level, then I couldn't inject the current user in the graphql context either, so I would have to add it to the `request.state` and access it directly on every resolver. So I figured I would just add the auth at the graphql middleware level, or the `on_schema` directive in this case.

**Comment by daveoconnor** [comment]
Sorry if I'm butting in here out of place but trying to do auth via middleware was a problem I was facing too and I asked in the chat and they suggested doing it via aiohttp middleware. I worked but was a little more cumbersome than I thought would be ideal so I created something a while back that I think may help. 

https://github.com/daveoconnor/tartiflette-request-context-hooks

Maybe I should have called it tartiflette-request-context-middleware. Naming is hard :)

It currently only supports aiohttp but while developing it I intentionally tried to design it so that support for additional servers could be added relatively easily. Adding asgi support would be the first test of that.

**Comment by sebastiandev** [comment]
I'm trying to do the same but the problem is that I'm using FastAPI and mounting a tartiflette app with tartiflete-asgi. I've created [this question](https://stackoverflow.com/questions/64504606/tartiflette-fastapi-auth) in stackoverflow. The problem lies in how tartiflette-asi integrates with asgi servers, is not easy to use the FastApi goodies like dependencies.  I was going to go for the http auth approach, problem is I cannot inject the authenticated user in the graphql context because that is not available at that time (I'm used to graphene, that the view is created with the current request where I can get the current user from flask-login library).

So the options I have are:
 - do it at the http level with a middleware and store the user in the request global state, and access this through `context.req`
 - do it as a schema directive in tratiflette. This is a bit cumbersome because if I need auth for other rest endpoints then I have to apply the validation in 2 places. Also I've encountered an error when raising exceptions in the `on_schema` directive, issue created [here](https://github.com/tartiflette/tartiflette/issues/453)

**Comment by daveoconnor** [comment]
You lost me with the FastAPI details. I haven't used it but it seems strange to me that FastAPI is in the mix here at all.  It makes more sense to me that someone would just use [tartiflette-asgi](https://github.com/tartiflette/tartiflette-asgi) and keep FastAPI out of the loop completely, but maybe I'm not aware of something about your setup. It just makes for a simpler system in my eyes. 

It sounds to me like my package will fit what you want in point 1 but in an easier way than if you were to try implementing it yourself. 

For example, the way I'm doing JWT handling is roughly along the lines of:

1. Create a fairly standard python async context manager (for my hooks middleware-ish package) which intercepts the request headers in the authentication data in the __aenter__ method. 
1.  The method then gets the user data from the database based on the parsed authentication data.
1. The method then saves the user data via the hook package methods documented, and makes it very easily accessible in the context across multiple queries per request. That's handling the "global storage" you were talking about.

If that sounds right to you what you would need to do is implement the asgi support as a module here: https://github.com/daveoconnor/tartiflette-request-context-hooks/tree/master/tartiflette_request_context_hooks/middleware, ideally with a matching method signature, or if not feasible to do that, a check and a change of how it's called in the main body of code.

p.s. I plan on making the JWT package available too but it's not complete yet and it'll probably be some time before it is. If you're auth is JWT based and you're interested in collaborating let me know and maybe we can figure something out there too.

**Comment by sebastiandev** [comment]
I'm might be completely wrong, but, for example we need `/health` endpoints, and those are usually simple rest ones. We have always approached the graphql apps by mounting them in a flask or fastapi server.

We are not really doing full blown oauth in this particular app, its just a token or api key sent as a header that we just validate and use to get the actual user.

How would a plain asgi approach look like without the FastApi thing? (I'm gonna take a closer look at you library tomorrow)

**Comment by daveoconnor** [comment]
Sounds like you're replying based on the email you'd have gotten from github. I've deleted that paragraph questioning the use of FastAPI because I'm probably just out of the loop there so let's just pretend I didn't comment about that :) 

It's worth reading my updated comment from this thread rather than the initial email you got. I've clarified some details that might help.

**Comment by abusi** [comment]
@sebastiandev At the core, tartiflette is only a graphql executor, you could do.


``` 
from tartiflette import Engine
_ENGINE = Engine(...)

app = fastapi(...)

@app.on_event("startup")
async def on_start(app):
   await _ENGINE.cook(...)
```

@app.post("/graphql")
async def graphql_ninja(... = Depends(...)):
      ....
      data: Dict[str,Any] = _ENGINE.execute(...)
      ....
```

And thus use any fastapi thing you want for you environment.
Tartiflette is only "in charge" of the GraphQL side of the query.

On the fastapi compatibily of tartiflette-asgi I'd really like to pick the mind of @florimondmanca which is the one that did the tartiflette-asgi integration, he may have good insight on this case.

**Comment by sebastiandev** [comment]
@abusi Ah! that sounds like what I need. I didn't realize about that, I was just determined to make it work with tartiflette-asgi but this looks just perfect. Thanks!

@daveoconnor I will still take a look at you suggestion It might come handy eventually, so thanks for the tip as well.

**Comment by sebastiandev** [comment]
I've borrowed some code from tartiflette-asgi and created this class to wrap the whole thing
```python
class GraphQLApp:

    def __init__(self, app, modules, schema_path=None, error_coercer=None):
        self.engine = Engine(
            sdl=os.path.join(os.path.dirname(__file__), "schema"),
            modules=modules,
            error_coercer=error_coercer,
        )

        app.on_event("startup")(self._cook)

    async def _cook(self):
        await self.engine.cook()

    def _build_context(self, **kwargs):
        return kwargs or {}  # add custom logic when needed here

    async def _get_response(self, request: Request, data: QueryParams, context: dict) -> Response:
        try:
            query = data["query"]
        except KeyError:
            return PlainTextResponse("No GraphQL query found in the request", 400)

        def _format_error(error: typing.Any) -> dict:
            import ast

            try:
                return ast.literal_eval(str(error))
            except ValueError:
                return {"message": "Internal Server Error"}

        background = BackgroundTasks()
        context = {"req": request, "background": background, **self._build_context(**context)}

        result: dict = await self.engine.execute(
            query,
            context=context,
            variables=data.get("variables"),
            operation_name=data.get("operationName"),
        )

        content = {"data": result["data"]}
        has_errors = "errors" in result
        if has_errors:
            content["errors"] = [_format_error(error) for error in result["errors"]]

        status = 400 if has_errors else 200
        return JSONResponse(content=content, status_code=status, background=background)

    async def process_request(self, request: Request, context: dict = None) -> Response:
        content_type = request.headers.get("Content-Type", "")
        if "application/json" in content_type:
            try:
                data = await request.json()
            except json.JSONDecodeError:
                return JSONResponse({"error": "Invalid JSON."}, 400)

        elif "application/graphql" in content_type:
            body = await request.body()
            data = {"query": body.decode()}

        elif "query" in request.query_params:
            data = request.query_params

        else:
            return PlainTextResponse("Unsupported Media Type", 415)

        return await self._get_response(request, data=data, context=context or {})
```

When processing a request we can send any custom context we need to inject in the graphql context. So we can use that to add the current user or any other data.

**Comment by abusi** [comment]
I think we can consider this closed :D
