### ISSUE TITLE
forcefully unregister all resolvers for debug purposes

### ISSUE THREAD

**Issue by Lilja** [tartiflette/tartiflette#476]
## new feature: forcefully unregister all resolvers for debug purposes

I'm using sanic as the HTTP server for my app. I'm passing the `debug` parameter set to true to the `run()` method which reloads the application and restarts the server when it detects changes.

My graphql-related parts. Bear in mind I'm a beginner to graphql!

```python
from tartiflette import Resolver, create_engine, Engine
from aiohttp import ClientSession
from .client import Hubspot
from .Entities import Stages
import aiofiles
import os

async def get_stages(hubspot: Hubspot) -> Stages:
    return await hubspot.get_pipeline(os.environ["HUBSPOT_PIPELINE"])


async def setup_graphql() -> Engine:
    async with ClientSession() as session:
        hubspot = Hubspot(session)
        stages = await get_stages(hubspot)

    @Resolver("Query.getRequestsByAccountID")
    async def resolve_get_requests_by_account_id(parent, args, ctx, info):
        return await hubspot.get_request_by(stages)


    async with aiofiles.open('../schema.graphql', mode='r') as f:
        return await create_engine(await f.read())


async def query(body: str):
    return await create_engine(body)

```

Saving this and letting sanic re-load the files results in the following error:

```
Traceback (most recent call last):
  File "/Users/lilja/Library/Caches/pypoetry/virtualenvs/backend-dmp__8h8-py3.8/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "src/run", line 18, in run_submit
    await lambda_handler.local_handler(
  File "/Users/lilja/code/umbrella/customs-data-form/backend/src/data_request_form_api/lambda_handler.py", line 56, in local_handler
    await setup_graphql()
  File "/Users/lilja/code/umbrella/customs-data-form/backend/src/data_request_form_api/service.py", line 24, in setup_graphql
    async def resolve_get_requests_by_account_id(parent, args, ctx, info):
  File "/Users/lilja/Library/Caches/pypoetry/virtualenvs/backend-dmp__8h8-py3.8/lib/python3.8/site-packages/tartiflette/resolver/resolver.py", line 113, in __call__
    SchemaRegistry.register_resolver(self._schema_name, self)
  File "/Users/lilja/Library/Caches/pypoetry/virtualenvs/backend-dmp__8h8-py3.8/lib/python3.8/site-packages/tartiflette/schema/registry.py", line 112, in register_resolver
    SchemaRegistry._register(schema_name, "resolvers", resolver)
  File "/Users/lilja/Library/Caches/pypoetry/virtualenvs/backend-dmp__8h8-py3.8/lib/python3.8/site-packages/tartiflette/schema/registry.py", line 79, in _register
    raise ImproperlyConfigured(
tartiflette.types.exceptions.tartiflette.ImproperlyConfigured: Can't register < Query.getRequestsByAccountID > to < default > resolvers because it's already registered
```

It would be great if it were possible to be able replace the old resolver implementations if so desired!

**Comment by abusi** [comment]
Hi @Lilja,

In tartflette schema and resolver only need to be associated once, then for the while life of the schema object, it's the same resolver that is called.

I don't quite understand why you'll would want to do this :).

In your example, in the query, what is body ? a new SDL or a graphql request ?

**Comment by Lilja** [comment]
Hi @abusi!

> In tartflette schema and resolver only need to be associated once, then for the whole life of the schema object, it's the same resolver that is called.

That is completely reasonable from a production standpoint, the problem is that for debug/developing. Hot reloading is a great feature that would allow me stop not having to `make serve`/`python app.py` and then re-start the server manually when a file is edited.

To work around this issue, I need to switch from my editor and go to my terminal, hit `Ctrl-C` and restart my `poetry run python src/run` command every time I want to re-reload the files. One of those file changes could be the implementation of `resolve_get_requests_by_account_id` in this scenario, which would be amazing if it just didn't trigger the exception below and re-write the changes.

[The problem exception](https://github.com/tartiflette/tartiflette/blob/ec25e62c275b832b4504c0f8d840b705369af79f/tartiflette/schema/registry.py#L79)

> In your example, in the query, what is body ? a new SDL or a graphql request ?

Not exactly relatable, but I guess I could show you anyway. I indent to use this in an AWS lambda in production. So I'm using sanic as a temporary framework for developing. Body is the request.json from the http-request.

```python
#!/usr/bin/env python3

from data_request_form_api import lambda_handler
from sanic import Sanic
from sanic.response import json
from sanic_cors import CORS

app = Sanic(name="localhost_app")
CORS(app)


@app.route("/", methods=["POST", "OPTIONS"])
async def run_submit(request):
    event = {
        "headers": request.headers,
        "body": request.json,
    }
    return json(
        await lambda_handler.local_handler(
            event,
            {}
        )
    )

app.run(host="0.0.0.0", port=8000, debug=True)
```

And then in `lambda_handler#local_handler`: 

```python
from typing import Dict, Any
import json
import os
import asyncio
from .auth import do_stuff
from .service import setup_graphql, query
import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

async def local_handler(event: Dict[str, Any], context: Any):
    await setup_graphql()
    query_resp = await query(event["body"])

    return {
        "statusCode": 200,
        "body": json.dumps(query_resp),
        "headers": {
          'Access-Control-Allow-Origin': origin,
          'Access-Control-Allow-Credentials': True,
          'X-Test-Header': 'test'
        }
    }

```

**Comment by abusi** [comment]
Thanks for you example.
Sadly, for tartiflette to work, schema need to be "baked", which means analyzed and transform into a data structure that needs to constructed. If we let resolver be overriden, each time you'll associate a method with a field via the @resolver we would have to reconstruct the whole execution structure (it's a big partial() graph of some sort to sum it up badly). 

I'll recommend you to use `python-watchdog watchmedo` python package which will restart everything each time a file is modified. It works very fine.

**Comment by Lilja** [comment]
Thanks for the reply. I interpret from you that it's not a quickwin, easy to add feature. I'll close the issue then.

As for the `watchmedo`/hot-reloading part. I tried watchmedo, which didn't work great with sanic. I got an error that would indicate that the app tries to re-bind the address `0.0.0.0` and port `8000` when it was already bound. I then saw that `sanic`'s `app.run()` has the `debug` property which hot-reloads everything. Which is why I created this issue.

I think I will replace the tooling with `nodemon` which might handle http-servers correctly.

**Comment by Lilja** [comment]
Just wanted to add some more context to this issue. I deployed the function to a lambda and because of AWS lambda's feature of keeping lambdas hot and re-running the code instead of having a cold start the code will trigger an `ImproperlyConfigured` error.

This means that if it runs the `Resolve` decorator, the code will run into an `ImproperlyConfigured` error.

Here is an invoke of the lambda, the first request resolves. The second time lambda will re-use the same instance 17 minutes later and run into this error:
![image](https://user-images.githubusercontent.com/6134511/114421395-8d7b8380-9bb5-11eb-868f-6b35e46b8066.png)

**Comment by abusi** [comment]
Yeah :'(, not really cool. I really don't know how AWS Lambda works and how Tartiflette could evolve in order to support it.
Feel free to do a PR with what you think could be a solve for this and I'll gladly look at it.
