### ISSUE TITLE
Error coercers should not wrap custom exceptions inside Tartiflette errors

### ISSUE THREAD

**Issue by arugifa** [tartiflette/tartiflette#577]
I am trying to use error coercers, in order to raise custom exceptions in my resolvers, and provide different error handling based on exception types.

For that, I followed the [official documentation](https://tartiflette.io/docs/api/error-handling), and created a small Tartiflette app to play with:

```python
import logging

from aiohttp import web
from tartiflette import Engine, Resolver
from tartiflette_aiohttp import register_graphql_handlers


class CustomException(Exception):
    def __init__(self, type_name, message):
        self.type = type_name
        self.message = message


async def my_error_coercer(exception, error):
    import pdb
    pdb.set_trace()

    if isinstance(exception, CustomException):
        logging.error("Unable to reach the Storage host.")
        error["extensions"]["type"] = exception.type

    return error


@Resolver("Query.hello")
async def resolver_hello(parent, args, ctx, info):
    raise CustomException("exception_type", "exception message")
    return "hello " + args["name"]


sdl = """
    type Query {
        hello(name: String): String
    }
"""


def run():
    """
    Entry point of the application.
    """
    engine = Engine(sdl, error_coercer=my_error_coercer)

    web.run_app(
        register_graphql_handlers(
            app=web.Application(),
            engine=engine,
            executor_http_endpoint="/graphql",
            executor_http_methods=["POST"],
            graphiql_enabled=True,
        )
    )
```

However, it doesn't work as expected: custom errors raised inside a resolver keep being wrapped into `TartifletteError`s:

```python
> /home/tartiflette/recipes_manager/app.py(17)my_error_coercer()
-> if isinstance(exception, CustomException):
(Pdb) exception
TartifletteError(message="('exception_type', 'exception message')", locations=[Location(line=2, column=3, line_end=2, column_end=23)])
```

The exception's type is `TartifletteError`, and not `CustomException`, which prevents to run code based on exception types.

I would expect to get access to the original exception instead, so I can freely use `isinstance()` function in my error coercers.

---

- Tartiflette version: _1.4.1_
- Python version: _3.10.5_

**Comment by abusi** [comment]
You should be able to access the original Exception using the `original_error` attribute to access your CustomException. We may need to update the documentation on that.

**Comment by arugifa** [comment]
@abusi Indeed: I can access to the original exception via the `original_error` attribute.

Thanks a lot 🙌
